DROP TABLE IF EXISTS UPL_CRM_ANAGRAFICA_AGENZIA;
CREATE TABLE UPL_CRM_ANAGRAFICA_AGENZIA
(ID_ANAGRAFICA_AGENZIA IDENTITY NOT NULL,
    ID_SOGGETTO BIGINT NOT NULL,
  RETE_VENDITA_DI_PROVENIENZA VARCHAR(1)  NOT NULL,
  AGENZIA_MADRE_ASSICURATIVA VARCHAR(5)  NOT NULL,
  AGENZIA_PREVALENTE VARCHAR(5),
         DATA_CESSAZIONE_CLIENTE Date,
  STATO_CLIENTE_AGENZIA VARCHAR(2),
  FLAG_CLIENTE_TOP VARCHAR(1),
         DATA_CLIENTE_TOP Date,
          SUBAGENZIA VARCHAR(5),
           PRODUTTORE VARCHAR(5),
            ZONA_TERRITORIALE VARCHAR(3),
             MODALITA_INCASSO VARCHAR(1),
          UTENTE_AGGIORNAMENTO VARCHAR(20),
  TIPOLOGIA_AVVISO VARCHAR(1),
     DATA_AGGIORNAMENTO TIMESTAMP,
    DATA_INSERIMENTO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
      UTENTE_INSERIMENTO VARCHAR(20) NOT NULL
);
