DROP TABLE IF EXISTS UPL_CRM_DATI_SOCIOECONOMICI;
CREATE TABLE UPL_CRM_DATI_SOCIOECONOMICI
(ID_DATI_SOCIOECONOMICI IDENTITY NOT NULL,
    ID_SOGGETTO BIGINT NOT NULL,
     COMPAGNIA  VARCHAR(1) NOT NULL,
     NOME_ENTITA_RIFERITA  VARCHAR(20) NOT NULL,
   ID_ENTITA_RIFERITA BIGINT NOT NULL,
    DATA_AGGIORNAMENTO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
          UTENTE_AGGIORNAMENTO VARCHAR(20),
    DATA_INSERIMENTO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UTENTE_INSERIMENTO VARCHAR(20) NOT NULL
);