DROP TABLE IF EXISTS UPL_CRM_OPTOUT;
CREATE TABLE UPL_CRM_OPTOUT
(
	ID_OPTOUT IDENTITY NOT NULL,
    ID_SOGGETTO BIGINT NOT NULL,
    DATA_INIZIO TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    DATA_FINE TIMESTAMP,
    DATA_AGGIORNAMENTO TIMESTAMP,
    UTENTE_AGGIORNAMENTO VARCHAR(20),
    AHD_REF  VARCHAR(100),
    CODICE_TIPO_OPTOUT  BIGINT NOT NULL,
    DATA_INSERIMENTO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UTENTE_INSERIMENTO VARCHAR(20) NOT NULL
);