DROP TABLE IF EXISTS UPL_CRM_ANAGRAFICHE_PF;
CREATE TABLE UPL_CRM_ANAGRAFICHE_PF
(ID_SOGGETTO BIGINT NOT NULL,
    CODICE_STATO_CIVILE BIGINT,
     CODICE_SETTORE BIGINT,
          CODICE_MERCATO_PREFERENZIALE BIGINT,
            SESSO VARCHAR(1),
       DATA_NASCITA TIMESTAMP,
    DATA_AGGIORNAMENTO  TIMESTAMP,
          UTENTE_AGGIORNAMENTO VARCHAR(20),
       NOME VARCHAR(100),
             COGNOME VARCHAR(100) NOT NULL,
                   NATURA_NOMINATIVO VARCHAR(20),
                         FLAG_STANDARDIZZAZIONE VARCHAR(1),
    DATA_INSERIMENTO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
      UTENTE_INSERIMENTO VARCHAR(20) NOT NULL
);
