DROP TABLE IF EXISTS UPL_CRM_ANAG_REL;
CREATE TABLE UPL_CRM_ANAG_REL
(ID_ANAG_REL IDENTITY NOT NULL,
    CODICE_TIPO_RELAZIONE BIGINT NOT NULL,
     DESCRIZIONE  VARCHAR(1),
       DATA_INIZIO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
            DATA_FINE TIMESTAMP,
   ID_SOGGETTO_ARRIVO BIGINT NOT NULL,
    ID_SOGGETTO_PARTENZA BIGINT NOT NULL,
    DATA_AGGIORNAMENTO TIMESTAMP,
          UTENTE_AGGIORNAMENTO VARCHAR(20),
    DATA_INSERIMENTO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UTENTE_INSERIMENTO VARCHAR(20) NOT NULL
);
