DROP TABLE IF EXISTS UPL_CRM_ANOMALIE_ANAGRAFICHE;
CREATE TABLE UPL_CRM_ANOMALIE_ANAGRAFICHE
(ID_ANOMALIA IDENTITY NOT NULL,
    ID_SOGGETTO BIGINT NOT NULL,
     UTENTE_CANCELLAZIONE  VARCHAR(20),
     UTENTE_INSERIMENTO VARCHAR(20) NOT NULL,
     CODICE_TIPO_ANOMALIA BIGINT NOT NULL,
          CODICE_STATO_ANOMALIA BIGINT,
       DATA_INIZIO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
            DATA_FINE TIMESTAMP,
  PROVENIENZA_ALERT VARCHAR(1000),
    DATA_AGGIORNAMENTO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
          UTENTE_AGGIORNAMENTO VARCHAR(20),
    DATA_INSERIMENTO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP()
);
