DROP TABLE IF EXISTS UPL_CRM_ANAGRAFICA_IDENTITA;
CREATE TABLE UPL_CRM_ANAGRAFICA_IDENTITA
(ID_ANAGRAFICA_IDENTITA IDENTITY NOT NULL,
    ID_SOGGETTO BIGINT NOT NULL,
     CODICE_TIPO BIGINT NOT NULL,
  VALORE VARCHAR(20),
    DATA_AGGIORNAMENTO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
          UTENTE_AGGIORNAMENTO VARCHAR(20),
    DATA_INSERIMENTO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
      UTENTE_INSERIMENTO VARCHAR(20) NOT NULL
);


