DROP TABLE IF EXISTS UPL_CRM_RECAPITI;
CREATE TABLE UPL_CRM_RECAPITI
(
	ID_RECAPITO IDENTITY NOT NULL,
	CODICE_TIPO_RECAPITO BIGINT NOT NULL,
    RECAPITO VARCHAR(255) NOT NULL,
    DATA_AGGIORNAMENTO TIMESTAMP,
    UTENTE_AGGIORNAMENTO VARCHAR(20),
    CODICE_USO_RECAPITO BIGINT NOT NULL,
    PROVENIENZA_RECAPITO VARCHAR(100),
    ID_SOGGETTO BIGINT NOT NULL,
    FLAG_MEMBRO_FAMIGLIA  VARCHAR(1),
    FLAG_PREFERITO  VARCHAR(1),
    DATA_INIZIO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    DATA_FINE TIMESTAMP,
    DATA_INSERIMENTO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UTENTE_INSERIMENTO VARCHAR(20) NOT NULL
);