DROP TABLE IF EXISTS UPL_CRM_DOCUMENTI;
CREATE TABLE UPL_CRM_DOCUMENTI
(ID_DOCUMENTO IDENTITY NOT NULL,
   ID_SOGGETTO   BIGINT NOT NULL,
	CODICE_STATO_DOCUMENTO  BIGINT,
    CODICE_TIPO_DOCUMENTO  BIGINT NOT NULL,
    NUMERO_DOCUMENTO  VARCHAR(50),
        DATA_INIZIO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
        DATA_FINE TIMESTAMP,
          DATA_EMISSIONE TIMESTAMP,
          DATA_AGGIORNAMENTO TIMESTAMP,
          UTENTE_AGGIORNAMENTO VARCHAR(20),
     DESCRIZIONE  VARCHAR(255),
        LOCALITA_RILASCIO_DOCUMENTO  VARCHAR(30),
 DATA_SCADENZA TIMESTAMP,
    DATA_INSERIMENTO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UTENTE_INSERIMENTO VARCHAR(20) NOT NULL
);
