DROP TABLE IF EXISTS UPL_CRM_NUCLEI;
CREATE TABLE UPL_CRM_NUCLEI
(
	ID_NUCLEO IDENTITY NOT NULL,
	CODICE_TIPO_NUCLEO  BIGINT NOT NULL,
    ID_SOGGETTO_CAPOGRUPPO  VARCHAR(30) NOT NULL,
    DATA_INIZIO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    DATA_FINE TIMESTAMP,
    DATA_AGGIORNAMENTO TIMESTAMP,
    UTENTE_AGGIORNAMENTO VARCHAR(20),
    CONTACT  VARCHAR(20) NOT NULL,
    RAGIONE_SOCIALE_CAPOGRUPPO  VARCHAR(255),
    DATA_INSERIMENTO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UTENTE_INSERIMENTO VARCHAR(20) NOT NULL
);