DROP TABLE IF EXISTS UPL_CRM_ANAGRAFICHE_PG;
CREATE TABLE UPL_CRM_ANAGRAFICHE_PG
(ID_SOGGETTO BIGINT NOT NULL,
      CODICE_RAMO BIGINT NOT NULL,
       CODICE_SETTORE BIGINT NOT NULL,
        DATA_COSTITUZIONE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
           CODICE_MERCATO_PREFERENZIALE BIGINT NOT NULL,
         DATA_AGGIORNAMENTO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
            UTENTE_AGGIORNAMENTO VARCHAR(20),
            NOME VARCHAR(255),
              DATA_INSERIMENTO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
                  UTENTE_INSERIMENTO VARCHAR(20) NOT NULL
);

