DROP TABLE IF EXISTS UPL_CRM_CONVENZIONI;
CREATE TABLE UPL_CRM_CONVENZIONI
(ID_CONVENZIONE BIGINT NOT NULL,
    CODICE_FISCALE  VARCHAR(255) NOT NULL,
     PROVENIENZA  VARCHAR(20) NOT NULL,
        CONVENZIONE  VARCHAR(255),
    DATA_AGGIORNAMENTO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
          UTENTE_AGGIORNAMENTO VARCHAR(20),
    DATA_INSERIMENTO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UTENTE_INSERIMENTO VARCHAR(20) NOT NULL
);
