DROP TABLE IF EXISTS UPL_CRM_NUCLEI_DETT;
CREATE TABLE UPL_CRM_NUCLEI_DETT
(
	ID_NUCLEI_DETT IDENTITY NOT NULL,
	ID_SOGGETTO  BIGINT,
    ID_NUCLEO  BIGINT NOT NULL,
    DATA_INIZIO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    DATA_FINE TIMESTAMP,
    DATA_AGGIORNAMENTO TIMESTAMP,
    UTENTE_AGGIORNAMENTO VARCHAR(20),
    RAGIONE_SOCIALE_CLIENTE  VARCHAR(255),
    DATA_INSERIMENTO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UTENTE_INSERIMENTO VARCHAR(20) NOT NULL
);