TRUNCATE TABLE UPL_CRM_DATI_SOCIOECONOMICI_PF_ERRORI;
INSERT INTO UPL_CRM_DATI_SOCIOECONOMICI_PF_ERRORI
(	ID_DATI_SOCIOECONOMICI_PF_ERRORI  ,
          ID_SOGGETTO  ,
           COMPAGNIA  ,
          DATA_AGGIORNAMENTO ,
         STATO_CIVILE_F,
                FLAG_FIGLI_F ,
              ANNO_FIGLIO_1_F ,
                ANNO_FIGLIO_2_F ,
                ANNO_FIGLIO_3_F ,
                ANNO_FIGLIO_4_F ,
                TITOLO_STUDIO_F ,
                 INT_FAIDATE_F ,
               INT_MUSICA_F ,
              INT_LETTURA_F ,
               INT_TECNO_F ,
                     INT_SPORT_F ,
             INT_VIAGGI_F ,
              INT_SALUTE_F ,
              INT_NATURA_F ,
              INT_VOLONT_F ,
              INT_FOTO_F ,
             INT_MOTORI_F ,
              INT_ENOGAS_F ,
              INET_LAVORO_F ,
               INET_SOCIAL_F ,
               INET_ACQUISTI_F ,
                 INET_APPL_F ,
                     CASA_PROPR_F ,
              CASA_AFFITTO_F ,
                CASA_SECONDA_F ,
                CASA_MUTUO_F ,
              TIPO_RISPARMIATORE_F ,
                      INFO_RISP_AUTO_F ,
                 INFO_INT_PENS_F ,
                INFO_RISP_NO_RISCHI_F ,
                     INFO_STUDIO_FIGLI_F ,
                    INFO_REND_CAP_F ,
                INFO_EREDITA_F ,
                INFO_ASSISTENZA_F ,
                   INFO_TERREMOTO_F ,
               INFO_DANNI_F ,
              INFO_INDENNIZZO_F ,
                   INFO_PERDITA_IMPIEGO_F ,
                       PREV_CAMBIO_AUTO_F ,
                   PREV_PENSIONE_F ,
                 PREV_MUTUO_F ,
              PREV_NUOVA_ATT_F ,
                 PREV_PROMOZIONE_F ,
                   PREV_VACANZA_F ,
                PREV_FINE_STUDIO_FIGLI_F ,
               PREV_CAMBIO_CASA_F ,
              REC_CELLULARE_F            ,
                REC_TELEFONO_F ,
                REC_FAX_F ,
                REC_MAIL_F ,
                PROFESSIONE_F ,
                FIRMA_1_F ,
                FIRMA_2_F ,
                LOG_ERRORI ,
                UTENTE_AGGIORNAMENTO,
          DATA_INSERIMENTO ,
          UTENTE_INSERIMENTO   )
VALUES
(1,1,'0','2022-12-20 00.00.00.0',default,default,default,default,default,default,default,default,default,default,default,default,'1','1',default,default,default,default,'1','1',default,default,default,default,default,default,default,default,default,default,default,default,default,default,default,default,'1','1',default,default,default,default,'1','1',default,default,default,default,default,default,default,default,default,default,default,default,'2022-12-20 00.00.00.0','NULL'),
(2,2,'0','2022-12-20 00.00.00.0',default,default,default,default,default,default,default,default,default,default,default,default,'2','2',default,default,default,default,'2','2',default,default,default,default,default,default,default,default,default,default,default,default,default,default,default,default,'2','2',default,default,default,default,'2','2',default,default,default,default,default,default,default,default,default,default,default,default,'2022-12-20 00.00.00.0','NULL'),
(3,3,'0','2022-12-20 00.00.00.0',default,default,default,default,default,default,default,default,default,default,default,default,'3','3',default,default,default,default,'3','3',default,default,default,default,default,default,default,default,default,default,default,default,default,default,default,default,'3','3',default,default,default,default,'3','3',default,default,default,default,default,default,default,default,default,default,default,default,'2022-12-20 00.00.00.0','NULL'),
(4,4,'0','2022-12-20 00.00.00.0',default,default,default,default,default,default,default,default,default,default,default,default,'4','4',default,default,default,default,'4','4',default,default,default,default,default,default,default,default,default,default,default,default,default,default,default,default,'4','4',default,default,default,default,'4','4',default,default,default,default,default,default,default,default,default,default,default,default,'2022-12-20 00.00.00.0','NULL'),
(5,5,'0','2022-12-20 00.00.00.0',default,default,default,default,default,default,default,default,default,default,default,default,'5','5',default,default,default,default,'5','5',default,default,default,default,default,default,default,default,default,default,default,default,default,default,default,default,'5','5',default,default,default,default,'5','5',default,default,default,default,default,default,default,default,default,default,default,default,'2022-12-20 00.00.00.0','NULL');