DROP TABLE IF EXISTS UPL_CRM_CLAIM;
CREATE TABLE UPL_CRM_CLAIM
(
    CLAIM_ID            IDENTITY        NOT NULL,
    ADMIN_REF_NUM       VARCHAR(150),
    CLAIM_NUMBER        VARCHAR(20),
    CLAIM_DETAIL_AMT    DECIMAL(17,3),
    CLAIM_PAID_AMT      DECIMAL(17,3),
    OUTSTANDING_AMT     DECIMAL(17,3),
    BENEFIT_CLAIM_AMT   DECIMAL(17,3),
    CLAIM_TP_CD         BIGINT          NOT NULL ,
    LOB_TP_CD           BIGINT,
    CLAIM_STATUS_TP_CD  BIGINT,
    CLAIM_CODE          VARCHAR(20),
    STATUS_DT           TIMESTAMP,
    CLAIM_INCURRED_DT   TIMESTAMP,
    REPORTED_DT         TIMESTAMP,
    DESCRIPTION         VARCHAR(255),
    LAST_UPDATE_DT      TIMESTAMP       NOT NULL    DEFAULT CURRENT_TIMESTAMP(),
    LAST_UPDATE_USER    VARCHAR(20)
);