DROP TABLE IF EXISTS UPL_CRM_CLAIMROLE;
CREATE TABLE UPL_CRM_CLAIMROLE
(
    CLAIM_ROLE_ID       IDENTITY    NOT NULL,
    CLAIM_ROLE_TP_CD    BIGINT      NOT NULL,
    CONT_ID             BIGINT      NOT NULL,
    CLAIM_ID            BIGINT      NOT NULL,
    END_DT              TIMESTAMP,
    LAST_UPDATE_DT      TIMESTAMP   NOT NULL    DEFAULT CURRENT_TIMESTAMP(),
    LAST_UPDATE_USER    VARCHAR(20)
);