#Test database
ANAGRAFICA_PERSISTENCE_DATASOURCE_URL=jdbc:db2://axtsdb201.servizi.gr-u.it:50000/MDMTEST:progressiveStreaming=2;
ANAGRAFICA_PERSISTENCE_DATASOURCE_DRIVER_CLASS_NAME=com.ibm.db2.jcc.DB2Driver
ANAGRAFICA_PERSISTENCE_DATASOURCE_USERNAME=db2crm
ANAGRAFICA_PERSISTENCE_DATASOURCE_PASSWORD=db2crm
HIBERNATE_DIALECT=org.hibernate.dialect.DB2Dialect
ENABLE_TEST_ENDPOINTS=true
spring.security.oauth2.resourceserver.jwt.public-key-location=${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_PUBLIC_KEY_LOCATION:classpath:certs/dev_certificate_publickey.pem}
management.endpoints.enabled-by-default=false
management.endpoint.health.enabled=true

#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

TZ=Europe/Rome

#monitoring settings ([team]-[applicazione]-[ambiente]-[componente])
APMENV_INTROSCOPE_AGENT_HOSTNAME=crmo-anagrafica-dev-gestione
GC_MAX_METASPACE_SIZE=180

#health check endpoint customization
management.endpoint.health.show-details=always

DB_POOL_SIZE=100
anagrafica.datasource.maximum-pool-size=${DB_POOL_SIZE}
anagrafica.datasource.keepaliveTime=30000
anagrafica.datasource.idleTimeout=0
ANAGRAFICA_DATASOURCE_CONNECTION_TIMEOUT=5000
anagrafica.datasource.connectionTimeout=${ANAGRAFICA_DATASOURCE_CONNECTION_TIMEOUT}

STS_URL=https://mpgw-eur.servizi.gr-u.it
STS_PATH=/sts/v1/token
STS_PROVIDE_TYPE=BASIC
STS_PROVIDE_DOMAIN=RACF
STS_REQUIRE_TYPE=JWT
STS_REQUIRE_DOMAIN=bdhknox
STS_SCOPE=bdhknox
STS_TOKEN=VVRBMDAyNjg6Q1NMQklHNjg=

TOKEN_CACHE_TTL=60
DOMAIN_CACHE_TTL_HH=24

feign.httpclient.disableSslValidation=true
feign.httpclient.enabled=false
feign.okhttp.enabled=true
feign.okhttp.disableSslValidation=true
