spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/vacation
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      fail-on-empty-beans: false

