# batch datasource
INTERNAL_BATCH_DATASOURCE_URL=jdbc:h2:file:./target/ATTIVITAbatchdb;AUTO_SERVER=TRUE
#INTERNAL_BATCH_DATASOURCE_URL=${DRAKKAR_BATCH_JOB_DB_URL:jdbc:h2:mem:ATTIVITAbatchdb}
INTERNAL_BATCH_DATASOURCE_USERNAME=${DRAKKAR_BATCH_JOB_DB_USER:sa}
INTERNAL_BATCH_DATASOURCE_PASSWORD=${DRAKKAR_BATCH_JOB_DB_PWD:password}
INTERNAL_BATCH_DATASOURCE_DRIVERCLASSNAME=org.h2.Driver
# input STGTEST datasource
STGDATASOURCE_URL=jdbc:db2://axtsdb201.servizi.gr-u.it:50000/STGTEST:progressiveStreaming=2;
STGDATASOURCE_USERNAME=db2crm
STGDATASOURCE_PASSWORD=db2crm
STGDATASOURCE_DRIVERCLASSNAME=com.ibm.db2.jcc.DB2Driver
# output MDMTEST datasource -> need by attivita-persistence library dependency
ATTIVITA_PERSISTENCE_DATASOURCE_URL=jdbc:db2://axtsdb201.servizi.gr-u.it:50000/MDMTEST:progressiveStreaming=2;
ATTIVITA_PERSISTENCE_DATASOURCE_USERNAME=db2crm
ATTIVITA_PERSISTENCE_DATASOURCE_PASSWORD=db2crm
ATTIVITA_PERSISTENCE_DATASOURCE_DRIVER_CLASS_NAME=com.ibm.db2.jcc.DB2Driver
# properties for job definition
READER_PAGE_SIZE=20000
# logging properties
### logs the SQL queries
LOGGING_LEVEL_ORG_HIBERNATE_SQL=DEBUG
### logs the prepared statement parameters
LOGGING_LEVEL_ORG_HIBERNATE_TYPE_DESCRIPTOR_SQL_BASICBINDER=DEBUG
### to make the printing SQL beautify
SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=TRUE
SPRING_JPA_SHOW_SQL=true
SPRING_JPA_PROPERTIES_HIBERNATE_SHOW_SQL=true
SPRING_H2_CONSOLE_ENABLED=true
SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
BATCH_DB_UPDATE_USER=attivita-batch
spring.batch.job.enabled=true

#Pool size should be around = ((cpu_core_count * 2) + effective_spindle_count)
#both pool sizes should be equal
BATCH_POOL_SIZE=4
DB_POOL_SIZE=4
input.datasource.maximum-pool-size=${DB_POOL_SIZE}

# properties for job definition
CHUNK_SIZE=51
PAGE_SIZE=51


ATTIVITA_PERSISTENCE_CLAIM_MDM_URL=http://axtsmdm02.servizi.gr-u.it:9080/com.ibm.mdm.server.ws.restful/resources/MDMWSRESTful
CONNECTION_TIMEOUT_MILLIS=3000
READ_TIMEOUT_MILLIS=3000

STS_URL=https://mpgw-svil.servizi.gr-u.it
STS_PATH=/sts/v1/token
STS_PROVIDE_TYPE=BASIC
STS_PROVIDE_DOMAIN=RACF
STS_REQUIRE_TYPE=JWT
STS_REQUIRE_DOMAIN=GRUPPOUNIPOL
STS_SCOPE=crmo
STS_TOKEN=VVRBMDAyOTU6VE9LOTVEUkE=

TOKEN_CACHE_TTL=60
ATTIVITA_BATCH_NAME=attivita

CLAIMS_URL=https://crmo-sinistri-gestione-dev.servizi.gr-u.it
CLAIMS_PATH=/api/sinistri/v1