#CONTABILITA PERSISTENCE
CONTABILITA_PERSISTENCE_DATASOURCE_URL=jdbc:db2://axtsdb201.servizi.gr-u.it:50000/MDMTEST:progressiveStreaming=2;
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
CONTABILITA_PERSISTENCE_DATASOURCE_DRIVER_CLASS_NAME=com.ibm.db2.jcc.DB2Driver
CONTABILITA_PERSISTENCE_DATASOURCE_USERNAME=db2crm
CONTABILITA_PERSISTENCE_DATASOURCE_PASSWORD=db2crm