spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    username: ${MAIL}
    password: ${MAIL_PASSWORD}
    test-connection: true
    properties:
      mail:
        smtp:
          socketFactory:
            port: 587
          auth: true
          starttls:
            enable: true
          ssl.trust: smtp.gmail.com
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
      debug: true

---
spring:
  config:
    activate:
      on-profile: debug
  jpa:
    show-sql: true
    hibernate:
      properties:
        hibernate:
          format_sql: true
  mail:
    properties:
      debug: true


