spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/shop
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      fail-on-empty-beans: false
  flyway:
    baselineOnMigrate: true
  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    username: ${MAIL}
    password: ${MAIL_PASSWORD}
    test-connection: true
    properties:
      mail:
        smtp:
          socketFactory:
            port: 587
          auth: true
          starttls:
            enable: true
          ssl.trust: smtp.gmail.com
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
      debug: true
file:
  product: C:\Users\Kuba\Desktop\images\
