spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/shop
    username: postgres
    password: postgres
    hikari:
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      fail-on-empty-beans: false
  flyway:
    baselineOnMigrate: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          ssl:
            trust: smtp.gmail.com
          auth: true
          starttls:
            enable: true
            required: true
        transport:
          protocol: smtp
file:
  product: C:\Users\Kuba\Desktop\images\
