DROP TABLE IF EXISTS ALL_TYPES_MODEL;
CREATE TABLE ALL_TYPES_MODEL  (
    BIG_INTEGER BIGINT,
    BIG_DECIMAL DECIMAL(16,2),
    A_LONG INTEGER,
    A_INTEGER INTEGER,
    STRING VARCHAR(255),
    FLAG BOOLEAN,
    SQL_TIMESTAMP TIMESTAMP,
    SQL_DATE TIMESTAMP,
    LOCAL_DATE_TIME TIMESTAMP,
    EMPTY_BIG_INTEGER BIGINT,
    EMPTY_LONG INTEGER
);