SINISTRO_PERSISTENCE_DATASOURCE_URL=jdbc:db2://axtsdb201.servizi.gr-u.it:50000/MDMTEST:progressiveStreaming=2;
SINISTRO_PERSISTENCE_DATASOURCE_DRIVER_CLASS_NAME=com.ibm.db2.jcc.DB2Driver
SINISTRO_PERSISTENCE_DATASOURCE_USERNAME=db2crm
SINISTRO_PERSISTENCE_DATASOURCE_PASSWORD=db2crm

sinistro.datasource.maximum-pool-size=20
sinistro.datasource.keepaliveTime=30000
#sinistro.datasource.idleTimeout=0
sinistro.datasource.connectionTimeout=500000