<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>it.unipol.drakkar.maven.config-archive-parent</groupId>
        <artifactId>config-archive-parent</artifactId>
        <version>1.3.0</version>
        <relativePath/>
    </parent>

    <groupId>it.unipolsai.crmo.anagrafica.gestione-config</groupId>
    <artifactId>gestione</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <!--
        la sezione dependencies deve essere popolata nel caso
        la configurazione applicativa dipenda da configurazioni globali. (vedi Global Config)
    -->
    <dependencies>
        <dependency>
            <groupId>it.unipol.drakkar.global-config.drakkar-environment</groupId>
            <artifactId>drakkar-environment</artifactId>
            <version>1.0.0</version>
            <classifier>config</classifier>
            <type>zip</type>
        </dependency>
    </dependencies>

</project>