DROP TABLE IF EXISTS UPL_CRM_CLAIMCONTRACT;
CREATE TABLE UPL_CRM_CLAIMCONTRACT
(
    CLAIM_CONTR_ID          IDENTITY    NOT NULL,
    CLAIM_ID                BIGINT      NOT NULL,
    CONTRACT_ID             BIGINT      NOT NULL,
    END_DT                  TIMESTAMP,
    LAST_UPDATE_DT          TIMESTAMP   NOT NULL    DEFAULT CURRENT_TIMESTAMP(),
    LAST_UPDATE_USER        VARCHAR(20)
);