#Test database
SINISTRO_PERSISTENCE_DATASOURCE_URL=jdbc:db2://axtsdb201.servizi.gr-u.it:50000/MDMTEST:progressiveStreaming=2;
SINISTRO_PERSISTENCE_DATASOURCE_DRIVER_CLASS_NAME=com.ibm.db2.jcc.DB2Driver
SINISTRO_PERSISTENCE_DATASOURCE_USERNAME=db2crm
SINISTRO_PERSISTENCE_DATASOURCE_PASSWORD=db2crm
HIBERNATE_DIALECT=org.hibernate.dialect.DB2Dialect
ENABLE_TEST_ENDPOINTS=true
spring.security.oauth2.resourceserver.jwt.public-key-location=${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_PUBLIC_KEY_LOCATION:classpath:certs/dev_certificate_publickey.pem}
management.endpoints.enabled-by-default=false
management.endpoint.health.enabled=true

TZ=Europe/Rome

#monitoring settings ([team]-[applicazione]-[ambiente]-[componente])
APMENV_INTROSCOPE_AGENT_HOSTNAME=crmo-sinistri-dev-gestione
GC_MAX_METASPACE_SIZE=180

#health check endpoint customization
management.endpoint.health.show-details=always

DB_POOL_SIZE=100
sinistro.datasource.maximum-pool-size=${DB_POOL_SIZE}
sinistro.datasource.keepaliveTime=30000
sinistro.datasource.idleTimeout=0
sinistro.datasource.connectionTimeout=500000